---
#Choose your own adventure
- name: Include appropriate tasks for Secure Cluster Configuration
  include: tasks/secure.yml
  when: k8s_secure_master == True

- name: Include appropriate tasks for Insecure Cluster Configuration
  include: tasks/insecure.yml
  when: k8s_secure_master == False

#firewalld
- name: Include firewalld tasks
  include: tasks/firewalld.yml
  when: k8s_firewalld == True
