- name: Configure master
  block:
    - shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address 192.168.2.240 --apiserver-cert-extra-sans {{inventory_hostname}}
      register: result
      until: result.rc == 0
      retries: 5
      delay: 3
    - file:
        path: $HOME/.kube
        state: directory
        mode: 0644
        owner: root
        group: root
    - copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        owner: root
        group: root
        mode: 0644
        remote_src: yes
    - shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      register: fnn_results
      until: fnn_results.rc == 0
      retries: 5
      delay: 3
    - debug: var=result

    #- name: Configure Nodesstdout_linstdout_lineses
    #- set_fact:
    #    cmd_fact: {{ item }}
    #      with_items: "{{ result.stdout_lines | regex_search('\\W+kubeadm\\s+join\\s+(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\:[0-9]{4}\\W+token\\s+\\S+\\W+discovery-token-ca-cert-hash\\s+\\S+') }}"
        #cmd_fact: |
        #  {{result.stdout_lines[0] |
        #  map('regex_findall', '\W+kubeadm\s+join\s+(?:[0-9]{1,3}\.){3}[0-9]{1,3}\:[0-9]{4}\W+token\s+\S+\W+discovery-token-ca-cert-hash\s+\S+') |
        #  map('join') | list }}
    #- debug: msg={{ cmd_fact }}
  when: hostvars[inventory_hostname].hostrole == 'master'


  #- name: Testing
#  set_fact:
#    test_var: |
#      {{ 'Some DNS servers are 8.8.8.8 and 8.8.4.4' | regex_findall('\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b') }}


#- name: Configure NODES
#  debug:
#    msg: "Join command is {{join_cmd}}"
# ^"  kubeadm\s+\w+\s+(?:[0-9]{1,3}\.){3}[0-9]{1,3}\:\d{4}\s+\W+\S+\s+\S+\s+\W+\S+\s+\S+\b
