---
- name: Setup epel repo
  yum: name=epel-release state=latest

- name: Configure repositories
  shell: /bin/yum clean all && /bin/yum repolist

- name: Ensure iptables services are not enabled
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    masked: yes
  with_items:
    - iptables
    - ip6tables
  register: task_result
  failed_when: "task_result|failed and 'could not' not in task_result.msg|lower"

- name: Install and start Docker
  yum: name='{{ docker_pkg }}' state=present

- name: Start Docker
  service: name=docker enabled=yes
  notify: Start Docker

- name: setup kubernetes repo
  copy:
    src: ../files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644

- name: Configure Systems SELinux
  lineinfile:
    path: /etc/sysconfig/selinux
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'

- name: Configure systems kernel parameters
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.bridge.bridge-nf-call-iptables= 1'

- name: Configure systems swap
  replace:
    path: /etc/fstab
    regexp: '^/dev/mapper/centos-swap'
    replace: ''#/dev/mapper/centos-swap swap                    swap    defaults        0 0
    backup: yes

- name: Install Kubernetes Pkages
  yum: name='{{ item }}' state=latest
  with_items: '{{ kubernetes_pkgs }}'
  notify: Start Kubelet Service
